#!/usr/bin/env bash

for x in $(ls *ssh-keys*tgz); do
  tar xzvf $x
  mv var/tmp/ssh-key-hunter-work/* .
done

for x in $(ls *.pub.md5.dat); do 
  name=$(echo $x | cut -d'.' -f1); 
  val=$(cat $x | cut -d' ' -f1); 
  echo "$name, $val"; 
  echo ", $(cat $name.pub.file.dat) ,"; 
  grep $val *authorized_keys.auth.catalog; 
  echo " "; 
done
